development:
  adapter: postgresql
  encoding: unicode
  database: RapGenius_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: RapGenius_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: RapGenius_production
  pool: 5
  username:
  password:
